[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "surfaces-gcmc"
version = "0.1.0"
description = "Predicting Surface Atomic Structures on Doped Perovskite Oxides Using Grand Canonical Monte Carlo"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Mengren Bill Liu" }
]
dependencies = [
    "numpy",
    "matplotlib",
    "pyyaml",
    "pymatgen",
    "m3gnet",
    "tensorflow"
]

[project.scripts]
# This creates easy-to-use terminal commands for your users
surfaces-gcmc-sampler = "surfaces_gcmc.sampler:main"
surfaces-surface-thermo = "surfaces_gcmc.surface_thermo:main"
surfaces-bulk-thermo = "surfaces_gcmc.bulk_thermo:main"
surfaces-competing-phases = "surfaces_gcmc.competing_phases:main"

[tool.setuptools.packages.find]
where = ["src"]